name: StyleLint

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**/*.scss'
  push:
    branches:
      - main
    paths:
      - 'src/**/*.scss'

jobs:
  stylelint:
    name: StyleLint

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i

      - name: Lint
        run: bun stylelint 'src/**/*.scss'
